package com.example.newproject.ui.api.models.UserInfo

data class userInfo(
    val backPassportPhoto: Any,
    val contactPhone: String,
    val documentNo: String,
    val documentSeries: String,
    val documentTypeId: Int,
    val documentValidTill: Any,
    val eMail: Any,
    val facePassportPhoto: Any,
    val familyStatusId: Int,
    val firstName: String,
    val frontFace: Any,
    val frontPassportPhoto: Any,
    val id: Int,
    val identificationNumber: String,
    val isValidDocument: Boolean,
    val issueAuthority: String,
    val issueDate: String,
    val lastName: String,
    val middleName: String,
    val nationalityID: Any,
    val registrationCityID: Any,
    val registrationCityName: String,
    val registrationFlat: String,
    val registrationHouse: String,
    val registrationStreet: String,
    val residenceCityID: Int,
    val residenceCityName: Any,
    val residenceFlat: String,
    val residenceHouse: String,
    val residenceStreet: String,
    val sideFace: Any,
    val status: Int
)